# Generated by Django 4.2.30 on 2026-07-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResumeClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_id", models.CharField(max_length=64)),
                ("candidate_name", models.CharField(max_length=200)),
                ("question_key", models.CharField(max_length=64)),
                ("question_text", models.TextField()),
                ("answer", models.BooleanField()),
                ("evidence", models.TextField(blank=True)),
                ("chunk_size", models.PositiveIntegerField()),
                ("overlap", models.PositiveIntegerField()),
                ("top_k", models.PositiveIntegerField()),
                ("model_name", models.CharField(max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["question_key", "candidate_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="resumeclassification",
            constraint=models.UniqueConstraint(
                fields=("candidate_id", "question_key"),
                name="unique_candidate_question",
            ),
        ),
    ]
