# Generated by Django 4.2.30 on 2026-07-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeclassification",
            name="output_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resumeclassification",
            name="prompt_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resumeclassification",
            name="total_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
