# Generated by Django 4.2.30 on 2026-07-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0002_resumeclassification_output_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeclassification",
            name="thinking_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
