# Generated by Django 4.2.30 on 2026-07-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0003_resumeclassification_thinking_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeclassification",
            name="latency_ms",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
